@startuml
class com.example.sharethecarv05.Entry {
~ String userName
~ String carId
~ DateRange dateRange
+ String getUserName()
+ void setUserName(String)
+ String getCarId()
+ void setCarId(String)
+ DateRange getDateRange()
+ void setDateRange(DateRange)
}


class com.example.sharethecarv05.UserAdapter {
- Context context
- View view
- LayoutInflater layoutInflater
- TextView userView
- User userObj
- List<User> usersLst
- ImageView imgTrash
+ View getView(int,View,ViewGroup)
}


class com.example.sharethecarv05.Car {
~ String id
~ String model
~ String bluetooth
+ void setModel(String)
+ void setNum(String)
+ String getId()
+ String getModel()
+ String getBluetooth()
+ void setBluetooth(String)
}


class com.example.sharethecarv05.PermissionManager {
+ {static} ArrayList<CarUser> carUsers
+ {static} DatabaseReference myPermissionRef
+ {static} ArrayList<CarUser> GetHashMApOfPermissionsFromDB()
+ {static} ArrayList<String> GetUserCars(User)
+ {static} void SetNewPermission(String,String)
+ {static} ArrayList<String> GetCarUsersWifawtUser(String,String)
+ {static} ArrayList<String> GetCarUsers(String)
+ {static} Boolean UserHasCarPermission(String,String)
+ {static} void RemovePermission(String,String)
+ {static} void RemovePermission(String)
}


class com.example.sharethecarv05.Coordinates {
~ long time
~ double latitude
+ long getTime()
+ void setTime(long)
+ double getLatitude()
+ void setLatitude(double)
+ double getLongitude()
+ void setLongitude(double)
}


class com.example.sharethecarv05.BluetoothBackgroundService {
- BluetoothAdapter bluetoothAdapter
- String connectedDeviceName
- boolean isBluetoothConnected
- TextToSpeech textToSpeech
- LocationCallback locationCallback
- FusedLocationProviderClient locationClient
- Location lastKnownLocation
- {static} float MIN_DISTANCE_CHANGE_FOR_UPDATES
- Timer locationSaveTimer
- LocationRequest locationRequest
- DatabaseReference databaseReference
- BroadcastReceiver bluetoothConnectionReceiver
+ IBinder onBind(Intent)
+ int onStartCommand(Intent,int,int)
+ void onDestroy()
- void stopLocationUpdates()
- void startLocationUpdates()
- boolean hasLocationPermissions()
+ void isBTDeviceRegisteredInDB(BluetoothDevice,BluetoothCheckCallback)
- void startForegroundService()
- void createLocationRequest()
- void buildLocationCallback()
+ void SetLoco(Location,String)
}


interface com.example.sharethecarv05.BluetoothBackgroundService$BluetoothCheckCallback {
~ void onResult(boolean)
}

class com.example.sharethecarv05.BootCompletedReceiver {
+ void onReceive(Context,Intent)
}

class com.example.sharethecarv05.CarActivity {
~ User user
~ Car car
~ TextView carModel
~ Button btnNewTime
~ ListView listView
~ EntryAdapter entryAdapter
~ Button btnDate
~ ImageButton btnBlue
~ Integer year
~ ArrayList<Entry> entries
~ String date
~ Dialog dialog
~ Button btnDialogSaveChanges
~ Entry edit
~ long time
~ double latitude
# void onCreate(Bundle)
+ void createEditEntryDialog(Entry)
+ ArrayList<Entry> getDayEntries()
+ void updateListView()
+ boolean onCreateOptionsMenu(Menu)
+ boolean onOptionsItemSelected(MenuItem)
+ void onClick(View)
+ void saveDate(Integer,Integer,Integer)
- void showDatePicker()
- void showBluetoothDevicesDialog()
- void checkAndSaveDevice(String)
+ void onMapReady(GoogleMap)
- void openGoogleMaps()
}


class com.example.sharethecarv05.ScheduleManager {
~ {static} ArrayList<Entry> entries
~ {static} DatabaseReference myScheduleRef
+ {static} ArrayList<Entry> GetHashMApOfEntrysFromDB()
+ {static} Boolean PersonTimeOverLapChecker(String,DateRange)
+ {static} Boolean CarTimeOverLapChecker(String,DateRange)
+ {static} Integer AddEntry(String,String,DateRange)
+ {static} Integer EditEntry(String,String,DateRange,Entry)
+ {static} void DeleteEntry(Entry)
+ {static} ArrayList<Entry> GetDateRangesForCar(String)
+ {static} ArrayList<Entry> GetDateRangesForUser(String)
+ {static} ArrayList<Entry> SortEntryArray(ArrayList<Entry>)
+ {static} void DeleteUsersEntries(String,String)
+ {static} void DeleteCarEntries(Car)
}


class com.example.sharethecarv05.EditCar_Activity {
~ SharedPreferences sharedPreferences
~ Dialog dialog
~ Button btnSCar
~ User user
~ ListView listView
~ CarAdapter carAdapter
~ Car temp
~ EditText carModel
~ Intent intent
~ TextView carNum
# void onCreate(Bundle)
+ void createpickerDialog()
+ void onClick(View)
}


class com.example.sharethecarv05.CarPermissionActivity {
~ ListView listView
~ Button btnAddUser
~ EditText editTextUser
~ UserAdapter userAdapter
~ User user
~ Car car
~ String u
~ TextView title
# void onCreate(Bundle)
+ void refresListView()
+ void onClick(View)
}


class com.example.sharethecarv05.CarAdapter {
- Context context
- View view
- LayoutInflater layoutInflater
- ImageView carImgView
- TextView carModelView
- Car carObj
- List<Car> carsLst
+ View getView(int,View,ViewGroup)
}


class com.example.sharethecarv05.MyService {
~ DatabaseReference myRef
~ FirebaseDatabase database
~ boolean first
+ IBinder onBind(Intent)
+ int onStartCommand(Intent,int,int)
+ void alert(String,String)
}


class com.example.sharethecarv05.New_Car_Activity {
~ Button btnCancel
~ EditText etCarNum
~ String carModel
~ User user
- {static} int CAMERA_REQUEST_CODE
- {static} int PERMISSION_REQUEST_CODE
- TextView textView
- {static} int REQUEST_CAMERA_COME
~ int SELECT_PICTURE
# void onCreate(Bundle)
+ void onClick(View)
+ void onItemSelected(AdapterView<?>,View,int,long)
+ void onNothingSelected(AdapterView<?>)
- void checkPermissionsAndOpenCamera()
- void openCamera()
# void onActivityResult(int,int,Intent)
~ void imageChooser()
- Uri getImageUri(Bitmap)
- void startCropActivity(Uri)
- void processImage(Uri)
- void displayTextFromImage(FirebaseVisionText)
}


class com.example.sharethecarv05.CarManager {
+ {static} DatabaseReference myCarRef
+ {static} HashMap<String,Car> hscars
+ {static} HashMap<String,Car> GetHashMApOfCarsFromDB()
+ {static} Boolean setNewCar(Car)
+ {static} void UpdateCar(String,String)
+ {static} ArrayList<Car> getCarsArray(ArrayList<String>)
+ {static} void DeleteCar(Car)
+ {static} void SetBluetooth(String,String)
}


class com.example.sharethecarv05.User {
~ String username
+ Boolean isPassword(String)
+ String getUsername()
+ String getPassword()
+ void setUsername(String)
+ void setPassword(String)
+ String getType()
+ void setType(String)
}


class com.example.sharethecarv05.DateRange {
~ Date dateStart
~ Integer day
+ Boolean overlap(DateRange)
+ Date getDateStart()
+ Date getDateEnd()
+ Integer getDay()
+ void setDay(Integer)
+ Integer getMonth()
+ void setMonth(Integer)
+ Integer getYear()
+ void setYear(Integer)
+ Integer getTimeForSort()
+ String StartTimeToString()
+ String EndTimeToString()
+ String DateToString()
}


class com.example.sharethecarv05.CarsActivity {
~ User user
~ CarAdapter carAdapter
~ ListView listView
~ TextView textviewWelcomeMessage
# void onCreate(Bundle)
+ boolean onCreateOptionsMenu(Menu)
+ boolean onOptionsItemSelected(MenuItem)
}


class com.example.sharethecarv05.UserManager {
+ {static} DatabaseReference myPersonRef
+ {static} HashMap<String,User> hsusers
+ {static} String activeUser
+ {static} void setActiveUser(String)
+ {static} Boolean setNewUser(User)
+ {static} HashMap<String,User> GetHashMApOfPersons()
+ {static} HashMap<String,User> GetHashMApOfPersonsFromDB()
+ {static} User getUser(String)
+ {static} void Update(User)
+ {static} ArrayList<User> GetUsers(ArrayList<String>)
}


class com.example.sharethecarv05.MainActivity {
~ Button btnLogin
~ String userName
~ EditText etUserName
~ EditText etLoginUserName
~ RadioButton rbKid
~ Dialog dialog
~ HashMap<String,User> per
~ User user
~ ImageView img
+ DatabaseReference myRef
+ FirebaseDatabase database
+ {static} int MY_PERMISSIONS_REQUEST_BLUETOOTH_CONNECT
# void onCreate(Bundle)
+ void createSignUpDialog()
+ void onClick(View)
- void startService()
}


class com.example.sharethecarv05.Kid {
}
class com.example.sharethecarv05.EntryAdapter {
- Context context
- View view
- LayoutInflater layoutInflater
- TextView endTime
- LinearLayout linearLayout
- List<Entry> entries
- ImageView menu
~ String userName
+ View getView(int,View,ViewGroup)
}


class com.example.sharethecarv05.CarUser {
~ String userName
~ String carId
+ String getUserName()
+ void setUserName(String)
+ String getCarId()
+ void setCarId(String)
+ String toString()
}


class com.example.sharethecarv05.Parent {
+ Boolean CreateCar(String,String)
}



android.widget.ArrayAdapter <|-- com.example.sharethecarv05.UserAdapter
java.io.Serializable <|.. com.example.sharethecarv05.Car
android.app.Service <|-- com.example.sharethecarv05.BluetoothBackgroundService
com.example.sharethecarv05.BluetoothBackgroundService +.. com.example.sharethecarv05.BluetoothBackgroundService$BluetoothCheckCallback
android.content.BroadcastReceiver <|-- com.example.sharethecarv05.BootCompletedReceiver
com.example.sharethecarv05.OnClickListener <|.. com.example.sharethecarv05.CarActivity
androidx.appcompat.app.AppCompatActivity <|-- com.example.sharethecarv05.CarActivity
com.example.sharethecarv05.OnClickListener <|.. com.example.sharethecarv05.EditCar_Activity
androidx.appcompat.app.AppCompatActivity <|-- com.example.sharethecarv05.EditCar_Activity
com.example.sharethecarv05.OnClickListener <|.. com.example.sharethecarv05.CarPermissionActivity
androidx.appcompat.app.AppCompatActivity <|-- com.example.sharethecarv05.CarPermissionActivity
android.widget.ArrayAdapter <|-- com.example.sharethecarv05.CarAdapter
android.app.Service <|-- com.example.sharethecarv05.MyService
com.example.sharethecarv05.OnClickListener <|.. com.example.sharethecarv05.New_Car_Activity
com.example.sharethecarv05.OnItemSelectedListener <|.. com.example.sharethecarv05.New_Car_Activity
androidx.appcompat.app.AppCompatActivity <|-- com.example.sharethecarv05.New_Car_Activity
java.io.Serializable <|.. com.example.sharethecarv05.User
java.io.Serializable <|.. com.example.sharethecarv05.DateRange
androidx.appcompat.app.AppCompatActivity <|-- com.example.sharethecarv05.CarsActivity
com.example.sharethecarv05.OnClickListener <|.. com.example.sharethecarv05.MainActivity
androidx.appcompat.app.AppCompatActivity <|-- com.example.sharethecarv05.MainActivity
java.io.Serializable <|.. com.example.sharethecarv05.Kid
com.example.sharethecarv05.User <|-- com.example.sharethecarv05.Kid
android.widget.ArrayAdapter <|-- com.example.sharethecarv05.EntryAdapter
java.io.Serializable <|.. com.example.sharethecarv05.Parent
com.example.sharethecarv05.User <|-- com.example.sharethecarv05.Parent
@enduml